### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by 31ank** [Nekos-life/nekos.py#1]
The command ```pip install -U https://github.com/Nekos-life/nekos.py``` is not working, tried it on linux and windows (python3.6). This error comes up:
```Collecting https://github.com/Nekos-life/nekos.py
  Downloading https://github.com/Nekos-life/nekos.py
     \ 61kB 364kB/s
  Cannot unpack file /tmp/pip-unpack-w816_6mo/nekos.py (downloaded from /tmp/pip-req-build-w9snidmt, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-w9snidmt
````
If you change the url to ```https://github.com/Nekos-life/nekos.py/archive/master.zip``` the command works

**Comment by AlexFlipnote** [comment]
Yeah my bad, I forgot to change it to the .zip file directly. If you could PR it that would be great, because I'm not home at the moment.

**Comment by 31ank** [comment]
created a pr
