### ISSUE TITLE
Typo in nekos/nekos.py

### ISSUE THREAD

**Issue by RioghanDer2te** [Nekos-life/nekos.py#3]
Line 25: "Random_hentai_gif"
Upper cased letter used in a list which is compared to `input.lower()`, which makes it impossible to use.

![image](https://user-images.githubusercontent.com/39881274/40887934-52b8518e-6750-11e8-97db-43154fb13290.png)

**Comment by AlexFlipnote** [comment]
Will fix tomorrow when I got time for it.

**Comment by AlexFlipnote** [comment]
This has been solved now
