### ISSUE TITLE
Issue with random_hentai_gif

### ISSUE THREAD

**Issue by RioghanDer2te** [Nekos-life/nekos.py#4]
Asking for "random_hentai_gif" raises the error `KeyError: 'url'`

![image](https://user-images.githubusercontent.com/39881274/40923500-3e93cf7e-6815-11e8-85bf-1f7e40a46923.png)

PS: Every other image works.

**Comment by AlexFlipnote** [comment]
Have you updated it?

**Comment by RioghanDer2te** [comment]
Yes, otherwise I would get `raise errors.InvalidArgument("You haven't added any valid arguments\nArguments: {}".format(possible))` as Exception, because "Random_hentai_gif" would still have a capital letter.

Maybe "Random_hentai_gif" has still a capital letter in the database or something like that 🤔

**Comment by AlexFlipnote** [comment]
I'll have a look when I can

**Comment by AlexFlipnote** [comment]
Fixed this issue, sorry for the trouble
